[project]
name = "diabetes-agenticgraphrag"
version = "0.1.0"
description = "GraphRAG with Agentic Workflow for Type 2 Diabetes Nursing Managment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fpdf2>=2.8.5",
    "google-genai>=1.61.0",
    "ipykernel>=7.1.0",
    "langchain>=1.2.7",
    "langchain-classic>=1.0.1",
    "langchain-core>=1.2.7",
    "langchain-experimental>=0.4.1",
    "langchain-google-genai>=4.2.0",
    "langchain-groq>=1.1.1",
    "langchain-huggingface>=1.2.0",
    "langchain-neo4j>=0.8.0",
    "langchain-ollama>=1.0.1",
    "langchain-openai>=1.1.7",
    "langchain-qdrant>=1.1.0",
    "llama-index>=0.14.13",
    "llama-parse>=0.6.54",
    "neo4j>=6.1.0",
    "openai>=2.16.0",
    "pdfplumber>=0.11.9",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "qdrant-client>=1.16.2",
    "ragas>=0.4.3",
    "rapidfuzz>=3.14.3",
    "reportlab>=4.4.9",
    "requests>=2.32.5",
    "streamlit>=1.53.1",
]
